# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66ae20a24b43b3c6d0ce084049dce9257d387deb149d6f677b05c22c2275e0aac59359b5be02f409bb42983c61c241c5e32283b01eab88148865f453f9c5d787

test:
  secret_key_base: 9cecbbab94e9a4170a10131189c07ed6bf600a7da3a8f80223dfb23c1a1893d108b500d299e9927e4ea9a60e174ed15d5beb0361892f6bebe45661fb16f3c1f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
